<?php

$labels = array();
$labels['planner'] = 'Planner';
$labels['plan'] = 'Plan';

$labels['new'] = 'New';
$labels['done'] = 'Done';
$labels['star'] = 'Star';
$labels['edit'] = 'Edit';
$labels['delete'] = 'Delete';

$labels['all'] = 'All';
$labels['starred'] = 'Starred';
$labels['today'] = 'Today';
$labels['tomorrow'] = 'Tomorrow';
$labels['week'] = 'Week';

$labels['syntax'] = 'Syntax';
$labels['help'] = 'To add a plan use the input above and specify "when" (a date and maybe a time) and "what".
	               If "when" is empty no date/time will be added.';
?>
