<?php

$labels = array();
$labels['planner'] = 'Planner';
$labels['plan'] = 'Plan';
$labels['preview'] = 'Preview';

$labels['new'] = 'New';
$labels['done'] = 'Done';
$labels['mark'] = 'Mark';
$labels['unmark'] = 'Unmark';
$labels['edit'] = 'Edit';
$labels['delete'] = 'Delete';

$labels['mark_done'] = 'Mark as done';
$labels['delete_plan'] = 'Delete plan';

$labels['all'] = 'All';
$labels['starred'] = 'Starred';
$labels['today'] = 'Today';
$labels['tomorrow'] = 'Tomorrow';
$labels['week'] = 'Week';

$labels['show_all'] = 'Show all plans';
$labels['show_starred'] = 'Show starred plans';
$labels['show_today'] = 'Show today\'s plans';
$labels['show_tomorrow'] = 'Show tomorrow\'s plans';
$labels['show_week'] = 'Show week plans';
$labels['show_done'] = 'Show done plans';

$labels['help'] = 'Help';
$labels['syntax'] = 'Syntax';
$labels['help_text'] = 'To add a plan use the input above and specify "when" (a date and maybe a time) and "what".
                        If "when" is empty no date/time will be added.';
	                    
$labels['default_list'] = 'Default list';
$labels['list_todo_always'] = 'Show todo-plans always';
$labels['preview_plan'] = 'Show plan preview';
$labels['show_birthdays'] = 'Show birthdays';

?>
