<?php

$labels = array();
$labels['planner'] = 'Planner';
$labels['plan'] = 'Plan';
$labels['preview'] = 'Preview';

$labels['new'] = 'Nieuw';
$labels['done'] = 'Klaar';
$labels['mark'] = 'Markeer';
$labels['unmark'] = 'Demarkeer';
$labels['edit'] = 'Wijzig';
$labels['delete'] = 'Verwijder';

$labels['all'] = 'Alle';
$labels['starred'] = 'Ster';
$labels['today'] = 'Vandaag';
$labels['tomorrow'] = 'Morgen';
$labels['week'] = 'Week';

$labels['show_all'] = 'Laat alle planns zien';
$labels['show_starred'] = 'Laat alle gemarkeerde plannen zien';
$labels['show_today'] = 'Laat plannen voor vandaag zien';
$labels['show_tomorrow'] = 'Laat plannen voor morgen zien';
$labels['show_week'] = 'Laat plannen voor deze week zien';
$labels['show_done'] = 'Laat afgeronde plannen zien';

$labels['help'] = 'Help';
$labels['syntax'] = 'Syntax';
$labels['help_text'] = 'Gebruik het veld hierboven om een plan toe te voegen en specificeer een "wanneer" (een datum en misschien een tijd) and "wat".
                        Als "wanneer" leeg is zal er geen datum/tijd worden toegevoegd.';
                      
$labels['default_list'] = 'Standaard lijst';
$labels['list_todo_always'] = 'Laat todo-plans altijd zien';
$labels['preview_plan'] = 'Laat plan voorbeeld zien';

?>
