<?php

$labels = array();
$labels['planner'] = 'Planner';
$labels['plan'] = 'Plan';

$labels['new'] = 'Nieuw';
$labels['done'] = 'Klaar';
$labels['mark'] = 'Markeer';
$labels['unmark'] = 'Demarkeer';
$labels['edit'] = 'Wijzig';
$labels['delete'] = 'Verwijder';

$labels['all'] = 'Alle';
$labels['starred'] = 'Ster';
$labels['today'] = 'Vandaag';
$labels['tomorrow'] = 'Morgen';
$labels['week'] = 'Week';

$labels['help'] = 'Help';
$labels['syntax'] = 'Syntax';
$labels['help_text'] = 'Gebruik het veld hierboven om een plan toe te voegen en specificeer een "wanneer" (een datum en misschien een tijd) and "wat".
	                    Als "wanneer" leeg is zal er geen datum/tijd worden toegevoegd.';
?>
